# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: purple
  font_size: M

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo blog theme powered by Hugo Blox Builder.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_search: true
    show_theme_chooser: true
    highlight_active_link: true

# Site footer
footer:
  copyright:
    notice: 'happy every day'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 
    content_dir: content
    branch: main
  comment:
    provider: 'disqus'
    disqus:
      shortname: 'hollyjyz'
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: true
  repository:
    url: 'https://github.com/HugoBlox/hugo-blox-builder/'
    content_dir: starters/blog/content
    branch: main
